version: '3.3'
services:
  redis:
    image: 'redis:alpine'
    networks:
      - redis
  moment:
    environment:
      REDIS: redis:6379
      THE_MOVIE_DB_ACCESS_TOKEN: <your-api-key>
    restart: on-failure
    build: .
    # Specify an array of ports to map
    ports:
      - '80:5868'
    networks:
      - redis
networks:
  redis:
    driver: bridge